services:
  gateway:
    image: sevenhallo-gateway:latest
    container_name: gateway
    command: start-dev
    ports:
      - "8003:8003"
    networks:
      - sevenhallo

volumes:
  gateway:

networks:
  sevenhallo:
    driver: bridge
    external: true
